services:
    service:
        image: 'application:latest'
        container_name: 'project-movie-app'
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 8080
        depends_on:
            - database
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db_src
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: admin
            SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

    database:
        container_name: 'project-movie-database'
        image: 'postgres:latest'
        restart: always
        ports:
            - 5432:5432
        expose :
            - 5432
        environment:
            POSTGRES_DB: db_src
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
